apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: product-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  template:
    metadata:
      labels:
        app: product-app  
    spec:
      containers: 
        - name: product-container
          image: amitpal83/product-service:1.0.1
          volumeMounts:
            - name: product-pod-volume
              mountPath: /app/data
          ports:
            - containerPort: 9080 
      volumes:
        - name: product-pod-volume
          emptyDir: {}